# Generated by Django 3.2.3 on 2021-05-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_customer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Direct Deposit')], default=1),
        ),
    ]
