# Generated by Django 3.2.3 on 2021-05-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_profile_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name_kanji',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name_romaji',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name_kanji',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name_romaji',
            field=models.CharField(max_length=35),
        ),
    ]
