# Generated by Django 3.2.3 on 2021-05-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_profile_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.IntegerField(choices=[(1, '徳島市'), (2, '阿南市'), (3, '小松島市')], default=1),
        ),
    ]
