# Generated by Django 3.2.3 on 2021-05-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_1',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_2',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_1_type',
            field=models.IntegerField(choices=[(1, '母'), (2, '父'), (3, '祖母'), (4, '祖父'), (5, '叔父'), (6, '叔母')], default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_2_type',
            field=models.IntegerField(choices=[(1, '母'), (2, '父'), (3, '祖母'), (4, '祖父'), (5, '叔父'), (6, '叔母')], default=1),
        ),
    ]
