# Generated by Django 3.2.3 on 2021-05-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210519_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_1_type',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, '母'), (2, '父'), (3, '祖母'), (4, '祖父'), (5, '叔父'), (6, '叔母')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_2_type',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, '母'), (2, '父'), (3, '祖母'), (4, '祖父'), (5, '叔父'), (6, '叔母')], default=0),
        ),
    ]
