# Generated by Django 3.2.3 on 2021-05-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20210519_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'Preschool (0 y.o.)')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_1_type',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, '自身'), (2, '母'), (3, '父'), (4, '祖母'), (5, '祖父'), (6, '叔父'), (7, '叔母')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_2_type',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, '自身'), (2, '母'), (3, '父'), (4, '祖母'), (5, '祖父'), (6, '叔父'), (7, '叔母')], default=0),
        ),
    ]
