# Generated by Django 3.2.3 on 2021-05-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20210521_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.IntegerField(choices=[(0, '-------'), (1, '徳島市'), (2, '阿南市'), (3, '小松島市')], default=1),
        ),
    ]
