# Generated by Django 3.2.3 on 2021-05-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.IntegerField(choices=[(0, '-------'), (1, '徳島市'), (2, '阿南市'), (3, '小松島市')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_method',
            field=models.IntegerField(choices=[(0, '-------'), (1, '月謝袋'), (2, '引き落とし')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.IntegerField(choices=[(0, '-------'), (1, '在学'), (2, '休校'), (3, '退校')], default=0),
        ),
    ]
