# Generated by Django 3.2.3 on 2021-05-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.IntegerField(choices=[(0, '-------'), (1, '入学希望'), (2, '在学'), (3, '休校'), (4, '退校')], default=0),
        ),
    ]
