# Generated by Django 3.2.3 on 2021-06-01 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_profile_birthday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='CustomerProfile',
        ),
    ]
