# Generated by Django 3.2.3 on 2021-06-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_alter_customerprofile_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='prefecture',
            field=models.IntegerField(choices=[(0, '-------'), (1, '徳島県'), (2, '香川県')], default=1),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='city',
            field=models.IntegerField(choices=[(0, '-------'), (1, '徳島市'), (2, '阿南市'), (3, '小松島市'), (4, '綾歌郡')], default=0),
        ),
    ]
