# Generated by Django 3.2.3 on 2021-06-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20210608_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='first_name_katakana',
            field=models.CharField(default='pending', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_name_katakana',
            field=models.CharField(default='pending', max_length=35),
            preserve_default=False,
        ),
    ]
