# Generated by Django 3.2.3 on 2021-06-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20210608_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='city',
            field=models.IntegerField(choices=[(0, '-------'), (1, '徳島市'), (2, '阿南市'), (3, '小松島市'), (4, '綾歌郡'), (5, '海部郡')], default=0),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='grade',
            field=models.IntegerField(choices=[(0, '-------'), (1, '0才'), (2, '1才'), (3, '2才'), (4, '3才'), (5, '年小'), (6, '年中'), (7, '年長'), (8, '小1'), (9, '小2'), (10, '小3'), (11, '小4'), (12, '小5'), (13, '小6'), (14, '中1'), (15, '中2'), (16, '中3'), (17, '高1'), (18, '高2'), (19, '高3'), (20, '大人')], default=0),
        ),
    ]
