# Generated by Django 3.2.3 on 2021-06-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_auto_20210610_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='city_1',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='city',
            field=models.IntegerField(choices=[(0, '-------'), (1, '徳島市'), (7, '鳴門市'), (3, '小松島市'), (2, '阿南市'), (8, '吉野川市'), (9, '阿波市'), (10, '美馬市'), (6, '板野郡'), (5, '海部郡'), (4, '綾歌郡')], default=0),
        ),
    ]
