# Generated by Django 3.2.3 on 2021-06-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_auto_20210613_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='city_1',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
