# Generated by Django 3.2.3 on 2021-06-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_rename_city_customerprofile_city_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='city_1',
            new_name='city_2',
        ),
    ]
