# Generated by Django 3.2.3 on 2021-06-13 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_rename_city_1_customerprofile_city_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='city_2',
            new_name='city',
        ),
    ]
