# Generated by Django 3.2.3 on 2021-06-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_auto_20210613_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='city',
        ),
    ]
