# Generated by Django 3.2.3 on 2021-06-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_remove_customerprofile_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='city_1',
            new_name='city',
        ),
    ]
