# Generated by Django 3.2.3 on 2021-07-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_rename_city_1_customerprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
