# Generated by Django 3.2.3 on 2021-07-23 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_customerprofile_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, '-------'), (1, 'カウンセリング'), (2, '体験レッスン'), (3, '入学')], default=0)),
                ('note_text', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile')),
            ],
        ),
    ]
