# Generated by Django 3.2.3 on 2021-07-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
