# Generated by Django 3.2.3 on 2021-07-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0034_alter_notes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='type',
            field=models.IntegerField(choices=[(0, '-------'), (1, 'カウンセリング'), (2, '体験レッスン'), (3, '入学'), (4, 'カウンセリング・体験レッスン')], default=0),
        ),
    ]
