# Generated by Django 3.2.3 on 2021-07-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_alter_notes_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='instructor',
            field=models.IntegerField(choices=[(0, '-------'), (1, '遠藤先生'), (2, 'ファーリス先生'), (3, '松内先生')], default=0),
        ),
    ]
