# Generated by Django 3.2.3 on 2021-08-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_notes_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='type',
            field=models.IntegerField(choices=[(0, '-------'), (1, 'カウンセリング'), (2, '体験レッスン'), (3, '入学'), (4, 'カウンセリング・体験レッスン'), (5, 'レッスン開始')], default=0),
        ),
    ]
