# Generated by Django 3.2.3 on 2021-08-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_alter_notes_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateField(),
        ),
    ]
