# Generated by Django 3.2.3 on 2021-09-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0049_auto_20210929_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='instructor_1',
            field=models.ManyToManyField(blank=True, to='customer.Instructor'),
        ),
    ]
