# Generated by Django 3.2.3 on 2021-09-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0050_notes_instructor_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='first_name_kanji',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='last_name_kanji',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='profile_img_url',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
