# Generated by Django 3.2.3 on 2021-09-29 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0051_auto_20210929_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='instructor_1',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
