# Generated by Django 3.2.3 on 2022-03-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0055_alter_notes_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfileChangelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date_time', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.IntegerField(choices=[(1, 'create'), (2, 'retrieve'), (3, 'update'), (4, 'delete')])),
            ],
        ),
    ]
