# Generated by Django 3.2.3 on 2022-03-06 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0056_customerprofilechangelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofilechangelog',
            old_name='change_date_time',
            new_name='changelog_date_time',
        ),
        migrations.RenameField(
            model_name='customerprofilechangelog',
            old_name='change_type',
            new_name='changelog_type',
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='changelog_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
