# Generated by Django 3.2.3 on 2022-03-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0058_customerprofilechangelog_changelog_customer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='address_1',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='address_2',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='archived',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='city',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='first_name_kanji',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='first_name_katakana',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='first_name_romaji',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='last_name_kanji',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='last_name_katakana',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='last_name_romaji',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='payment_method',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='phone_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='phone_1_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='phone_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='phone_2_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='post_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='prefecture',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customerprofilechangelog',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
