# Generated by Django 3.2.3 on 2022-03-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0060_auto_20220306_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofilechangelog',
            name='changelog_user',
            field=models.IntegerField(default=0),
        ),
    ]
