# Generated by Django 3.2.3 on 2022-03-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0061_alter_customerprofilechangelog_changelog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfileAccesslog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesslog_customer_profile', models.IntegerField(default=0)),
                ('accesslog_date_time', models.DateTimeField(auto_now_add=True)),
                ('accesslog_user', models.IntegerField(default=0)),
            ],
        ),
    ]
