# Generated by Django 3.2.3 on 2022-03-09 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0064_auto_20220307_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesChangelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changelog_note', models.IntegerField(default=0)),
                ('changelog_date_time', models.DateTimeField(auto_now_add=True)),
                ('changelog_user', models.IntegerField(default=0)),
                ('changelog_type', models.IntegerField(choices=[(1, 'create'), (2, 'retrieve'), (3, 'update'), (4, 'delete')])),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('type', models.IntegerField(default=0)),
                ('note_text', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile')),
                ('instructor_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
