# Generated by Django 3.2.3 on 2022-03-14 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0066_auto_20220314_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteschangelog',
            name='instructor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_2_mirror', to=settings.AUTH_USER_MODEL),
        ),
    ]
