# Generated by Django 3.2.3 on 2022-03-17 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0068_auto_20220318_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteschangelog',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile'),
        ),
        migrations.AlterField(
            model_name='noteschangelog',
            name='instructor_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteschangelog',
            name='instructor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_2_mirror', to=settings.AUTH_USER_MODEL),
        ),
    ]
