# Generated by Django 3.2.3 on 2022-12-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAnalyticsDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_date', models.DateField()),
                ('day_present_count', models.IntegerField(default=0)),
                ('day_absent_count', models.IntegerField(default=0)),
                ('day_pending_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceAnalyticsMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_start_date', models.DateField()),
                ('month_present_count', models.IntegerField(default=0)),
                ('month_absent_count', models.IntegerField(default=0)),
                ('month_pending_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceAnalyticsWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('week_present_count', models.IntegerField(default=0)),
                ('week_absent_count', models.IntegerField(default=0)),
                ('week_pending_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLifetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('lifetime_all', models.IntegerField()),
            ],
        ),
    ]
