# Generated by Django 3.2.3 on 2022-12-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlifetime',
            name='lifetime_all_med',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
