# Generated by Django 3.2.3 on 2023-01-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_lifetime_all_studentlifetime_lifetime_all_mean'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('pre_0', models.IntegerField()),
                ('pre_1', models.IntegerField()),
                ('pre_2', models.IntegerField()),
                ('pre_3', models.IntegerField()),
                ('kin_1', models.IntegerField()),
                ('kin_2', models.IntegerField()),
                ('kin_3', models.IntegerField()),
                ('ele_1', models.IntegerField()),
                ('ele_2', models.IntegerField()),
                ('ele_3', models.IntegerField()),
                ('ele_4', models.IntegerField()),
                ('ele_5', models.IntegerField()),
                ('ele_6', models.IntegerField()),
                ('mid_1', models.IntegerField()),
                ('mid_2', models.IntegerField()),
                ('mid_3', models.IntegerField()),
                ('hig_1', models.IntegerField()),
                ('hig_2', models.IntegerField()),
                ('hig_3', models.IntegerField()),
                ('adu_1', models.IntegerField()),
            ],
        ),
    ]
