# Generated by Django 3.2.3 on 2023-01-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_studentdemographics'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonsPerStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('lessons_per_student', models.FloatField()),
            ],
        ),
    ]
