# Generated by Django 3.2.3 on 2023-02-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20230207_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsperstudent',
            name='multi_lesson_student_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
