# Generated by Django 4.1.3 on 2023-05-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0073_alter_notes_type'),
        ('analytics', '0011_alter_studentsinout_students_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinout',
            name='students_in',
            field=models.ManyToManyField(related_name='CustomerProfileIn', to='customer.customerprofile'),
        ),
        migrations.AlterField(
            model_name='studentsinout',
            name='students_out',
            field=models.ManyToManyField(related_name='CustomerProfileOut', to='customer.customerprofile'),
        ),
    ]
