# Generated by Django 3.2.3 on 2022-04-25 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0071_delete_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassListChangelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changelog_class', models.IntegerField(default=0)),
                ('changelog_date_time', models.DateTimeField(auto_now_add=True)),
                ('changelog_user', models.IntegerField(default=0)),
                ('changelog_type', models.IntegerField(choices=[(1, 'create'), (2, 'retrieve'), (3, 'update'), (4, 'delete')], default=0)),
                ('class_name', models.CharField(max_length=512)),
                ('primary_instructor', models.IntegerField(blank=True, default=0, null=True)),
                ('irregular', models.BooleanField(default=False)),
                ('day_of_week', models.IntegerField(blank=True, default=7, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('students', models.CharField(blank=True, max_length=1024, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('class_type', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=512)),
                ('irregular', models.BooleanField(default=False)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(7, '-------'), (0, '日曜日'), (1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日'), (6, '土曜日')], default=7, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('class_type', models.IntegerField(blank=True, choices=[(0, '-------'), (1, '英会話 ベビー'), (2, '英会話 未就学児 前半'), (3, '英会話 未就学児 後半）'), (4, '英会話 小学生'), (5, '英会話 中学生'), (6, '英会話 高校生'), (7, '英会話 大人'), (10, '英検 小学生'), (11, '英検 中学生'), (12, '英検 高校生'), (13, '英検 大人'), (14, '英文法 小学生'), (15, '英文法 中学生'), (16, '英文法 高校生'), (17, '英文法 大人'), (8, '個人 ４０分'), (9, '個人 ５０分')], default=0, null=True)),
                ('primary_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, to='customer.CustomerProfile')),
            ],
        ),
    ]
