# Generated by Django 3.2.3 on 2022-06-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='class_type',
            field=models.IntegerField(blank=True, choices=[(0, '-------'), (1, '英会話 ベビー'), (2, '英会話 未就学児 前半'), (3, '英会話 未就学児 後半'), (4, '英会話 小学生'), (5, '英会話 中学生'), (6, '英会話 高校生'), (7, '英会話 大人'), (10, '英検 小学生'), (11, '英検 中学生'), (12, '英検 高校生'), (13, '英検 大人'), (14, '英文法 小学生'), (15, '英文法 中学生'), (16, '英文法 高校生'), (17, '英文法 大人'), (8, '個人 40分'), (9, '個人 50分')], default=0, null=True),
        ),
    ]
