# Generated by Django 4.1.3 on 2023-05-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='edition',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
