# Generated by Django 3.2.3 on 2022-11-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencepoints',
            name='transaction_description',
            field=models.CharField(max_length=200),
        ),
    ]
