# Generated by Django 3.2.3 on 2022-11-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0073_alter_notes_type'),
        ('game', '0002_alter_experiencepoints_transaction_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperiencePoints',
            new_name='ExperiencePoint',
        ),
    ]
