# Generated by Django 3.2.3 on 2022-11-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0073_alter_notes_type'),
        ('game', '0003_rename_experiencepoints_experiencepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_identifier', models.CharField(max_length=64)),
                ('linked_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='ExperiencePoint',
        ),
    ]
