# Generated by Django 3.2.3 on 2022-11-27 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0073_alter_notes_type'),
        ('game', '0004_auto_20221127_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardindex',
            name='linked_student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile'),
        ),
    ]
