# Generated by Django 3.2.3 on 2022-12-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_cardindex_linked_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardindex',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
