# Generated by Django 3.2.3 on 2021-06-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prev_page',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
