# Generated by Django 3.2.3 on 2021-06-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_prev_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='prev_page',
        ),
    ]
