# Generated by Django 3.2.3 on 2021-06-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_rename_city_1_customerprofile_city'),
        ('user_profile', '0003_remove_userprofile_prev_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='flagged_profiles',
            field=models.ManyToManyField(to='customer.CustomerProfile'),
        ),
    ]
