# Generated by Django 3.2.3 on 2021-06-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_rename_city_1_customerprofile_city'),
        ('user_profile', '0004_userprofile_flagged_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='flagged_profiles',
            field=models.ManyToManyField(blank=True, to='customer.CustomerProfile'),
        ),
    ]
