# Generated by Django 3.2.3 on 2021-07-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_userprofile_flagged_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_archived',
            field=models.BooleanField(default=False),
        ),
    ]
