# Generated by Django 3.2.3 on 2021-09-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_userprofile_display_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name_kanji',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_kanji',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_img_url',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
