# Generated by Django 3.2.3 on 2021-09-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0052_auto_20210929_0930'),
        ('user_profile', '0007_auto_20210929_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notes',
            field=models.ManyToManyField(blank=True, to='customer.Notes'),
        ),
    ]
