# Generated by Django 3.2.3 on 2021-09-30 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_userprofile_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notes',
        ),
    ]
