# Generated by Django 3.2.3 on 2021-12-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_rename_display_archived_userprofile_display_archived_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_archived_notes',
            field=models.BooleanField(default=False),
        ),
    ]
