# Generated by Django 3.2.3 on 2022-05-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_userprofile_display_only_flagged_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_archived_classes',
            field=models.BooleanField(default=False),
        ),
    ]
