# Generated by Django 3.2.3 on 2022-05-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_userprofile_display_archived_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_classes_day_of_week',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
