# Generated by Django 3.2.3 on 2022-05-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_userprofile_display_classes_instructors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_classes_day_of_week',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
