# Generated by Django 3.2.3 on 2022-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_alter_userprofile_display_classes_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='class_list_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notes_active',
            field=models.BooleanField(default=False),
        ),
    ]
