# Generated by Django 3.2.3 on 2022-06-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_auto_20220602_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name_katakana',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name_romaji',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_katakana',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_romaji',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
