# Generated by Django 3.2.3 on 2022-07-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_auto_20220621_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='attendance_record_active',
            field=models.BooleanField(default=False),
        ),
    ]
