# Generated by Django 3.2.3 on 2022-09-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_userprofile_attendance_record_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='attendance_expanded_view_active',
            field=models.BooleanField(default=False),
        ),
    ]
