# Generated by Django 3.2.3 on 2022-03-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesslog_url', models.CharField(max_length=128)),
                ('accesslog_date_time', models.DateTimeField(auto_now_add=True)),
                ('accesslog_user', models.IntegerField(default=0)),
            ],
        ),
    ]
