# Generated by Django 3.2.3 on 2022-04-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='accesslog_post_parameters',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
