# Generated by Django 3.2.3 on 2022-04-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_accesslog_accesslog_post_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='accesslog_get_parameters',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
