# Generated by Django 3.2.3 on 2022-06-09 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_list.classlist')),
            ],
        ),
    ]
