# Generated by Django 3.2.3 on 2022-07-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_list', '0002_alter_classlist_class_type'),
        ('attendance', '0003_attendance_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='linked_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='class_list.classlist'),
        ),
    ]
