# Generated by Django 4.1.3 on 2023-05-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_content_attendance_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
