# Generated by Django 4.1.3 on 2023-05-31 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_content_content_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='content',
            field=models.ManyToManyField(blank=True, to='attendance.content'),
        ),
    ]
